name: medapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  bloc: ^6.1.0
  cached_network_image: ^2.5.0
  cool_alert: ^1.0.3
  dio: ^3.0.10
  downloads_path_provider_28: ^0.1.0
  easy_localization: ^2.3.2
  empty_widget: ^0.0.1
  equatable: ^1.2.0
  firebase_remote_config: ^0.4.3
  flutter_bloc: ^6.0.0
  flutter_date_pickers: ^0.1.8
  flutter_easyloading: ^2.2.2
  flutter_html: ^1.2.0
  flutter_local_notifications: ^3.0.2
  flutter_offline: ^0.3.0
  flutter_rating_bar: ^3.0.0
  flutter_screenutil: ^3.2.0
  flutter_share: ^1.0.5
  flutter_spinkit: ^4.1.2+1
  flutter_staggered_grid_view: ^0.3.0
  flutter_swiper: ^1.1.6
  fluttertoast: ^7.1.6
  font_awesome_flutter: ^8.10.1
  get_it: ^5.0.1
  google_maps_flutter: ^1.0.6
  http: ^0.12.2
  image_picker: ^0.6.7+2
  meta: ^1.2.4
  open_file: ^3.0.3
  package_info: ^0.4.3+2
  path_provider: ^1.6.5
  percent_indicator: ^2.1.1+1
  permission_handler: ^4.4.0+hotfix.2
  qr_flutter: ^3.2.0
  shared_preferences: ^0.5.6
  shimmer: ^1.1.2
  url_launcher: ^5.7.10
  web_socket_channel: ^1.1.0
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  image_path: 'assets/images/launcher_ic.png'
  android: true
  ios: true
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # module:
  #   androidX: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/
    - assets/languages/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
